#!/usr/bin/env bash

# scrip name
script_name=$(basename $0)
# help text
help_text="${script_name} [-h|--help] : this message
${script_name} dir dir ... : search biggest directory in each of the dir\n"

# directory where this script is
[ -z "${bindir}" ] && bindir="$(cd $(dirname $0) || exit 1; pwd)"
# source tools
[ -f "${bindir}/include/common-bash.sh" ] && source ${bindir}/include/common-bash.sh

# no parameters, show help
[ $# -eq 0 ] && dohelp
# parameters in -h, --help, show help
case $1 in
  -h|--help)
    dohelp
    ;;
esac

# do the real work for each parameter
while [ $# -gt 0 ]
do
  current_dir="$1"
  shift
  if [ -d "${current_dir}" ]
  then
    file_mask="${current_dir}/*"
  else
    file_mask="${current_dir}"
  fi
  /usr/bin/printf "%-48s - $(du -sm ${file_mask} 2> /dev/null | sort -n | tail -1)\n" ${current_dir}
done
