#!/usr/bin/env bash

[ -z "${bindir}" ] && bindir=$(cd $(dirname $0); pwd)
[ -f "${bindir}/include/common-bash.sh" ] && source ${bindir}/include/common-bash.sh

function dohelp() {
  local exit_value=0
  local error_message=

  case "$#" in
    '1')
      exit_value=$1
      ;;
    '2')
      exit_value=$1
      shift
      error_message="$@"
      ;;
  esac
  [ -n "$error_message" ] && \
    echo "ERROR : @" 1>&2

cat << DOHELP
${script_name} [-h|--help] : this message
${script_name} dir dir ... : search biggest directory in each of
                             the dir
DOHELP

  exit ${exit_value}
}
